# TypeProf 0.21.7

# Classes
module Settings
  module Exports
    class BlockedAccountsController
      @export: bot

      def index: -> untyped

      private
      def export_data: -> untyped
    end
  end
end
