# TypeProf 0.21.7

# Classes
class CustomEmojiFilter
  KEYS: [:local, :remote, :by_domain, :shortcode]

  attr_reader params: untyped
  def initialize: (untyped params) -> void
  def results: -> untyped

  private
  def scope_for: (untyped key, untyped value) -> untyped
end
