# TypeProf 0.21.7

# Classes
class Relay
  @some_local_account: untyped

  def enable!: -> untyped
  def disable!: -> untyped

  private
  def follow_activity: (untyped activity_id) -> Hash[untyped, untyped]
  def unfollow_activity: (untyped activity_id) -> Hash[untyped, untyped]
  def some_local_account: -> untyped
  def ensure_disabled: -> nil
  def strip_url: -> untyped
end
