# TypeProf 0.21.7

# Classes
module Authorization
  def pundit_user: -> untyped
  def authorize: (*untyped noname) -> untyped
  def authorize_with: (untyped user, untyped record, untyped query) -> untyped
end
