# TypeProf 0.21.7

# Classes
module AccountCounters
  extend ActiveSupport::Concern

  ALLOWED_COUNTER_KEYS: [:statuses_count, :following_count, :followers_count]

  def increment_count!: (untyped key) -> nil
  def decrement_count!: (untyped key) -> nil
  def update_count!: (untyped key, Integer value) -> nil
  def account_stat: -> untyped

  private
  def save_account_stat: -> nil
end
