# TypeProf 0.21.7

# Classes
module Expireable
  extend ActiveSupport::Concern

  @expires_in: untyped

  def expires_in: -> nil
  def expires_in=: (untyped interval) -> untyped
  def expire!: -> untyped
  def expired?: -> untyped
  def expires?: -> untyped
end
