# TypeProf 0.21.7

# Classes
module StatusSnapshotConcern
  def edited?: -> untyped
  def build_snapshot: (?account_id: nil, ?at_time: nil, ?rate_limit: true) -> untyped
  def snapshot!: (**untyped) -> untyped
end
