# TypeProf 0.21.7

# Classes
class UnblockService
  def call: (untyped account, untyped target_account) -> nil

  private
  def create_notification: (untyped unblock) -> untyped
  def build_json: (untyped unblock) -> untyped
end
