default: styles/application.scss
kohaku: styles/application_kohaku.scss
mizuki: styles/application_mizuki.scss
orochi: styles/application_orochi.scss
creatodon: styles/application_creatodon.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mean-of-amber: styles/application_mean_of_amber.scss
aquamarine: styles/application_aquamarine.scss
meteor-trail: styles/application_meteor_trail.scss
mirroring: styles/application_mirroring.scss