# TypeProf 0.21.7

# Classes
module Settings
  module TwoFactorAuthentication
    class WebauthnCredentialsController
      def index: -> nil
      def new: -> nil
      def options: -> untyped
      def create: -> untyped
      def destroy: -> untyped

      private
      def require_otp_enabled: -> nil
      def require_webauthn_enabled: -> nil
    end
  end
end
