# TypeProf 0.21.7

# Classes
class ApplicationRecord
  def self.update_index: (untyped _type_name, *untyped _args) -> nil
  def boolean_with_default: (untyped key, untyped default_value) -> untyped
end
