name: Type Check

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

env:
  BUNDLE_CLEAN: true
  BUNDLE_FROZEN: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  steep-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up bundler cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true

      - name: Install rbs collection
        run: bundle exec rbs collection install

      - name: Running steep check
        run: bundle exec steep check
